version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.glassfish.jersey.core:jersey-client
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey.connectors:jersey-apache-connector
    versions:
    - 3.0.0
  - dependency-name: org.glassfish.jersey.media:jersey-media-json-jackson
    versions:
    - 3.0.0
